---
- name: "Debian - Minimal Dev Setup"
  hosts: debian-ipv4chat
  become: true
  gather_facts: false

  tasks:
    - name: Ensure resolv.conf has valid DNS
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8
          nameserver 1.1.1.1
        owner: root
        group: root
        mode: '0644'

    - name: Restart systemd-resolved if present
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted
      failed_when: false

    - name: Update apt repo and cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      retries: 3
      delay: 5

    - name: Install development tools
      ansible.builtin.apt:
        name:
          - gcc
          - g++
          - cmake
          - make
          - build-essential
        state: present
